import os
import re

corrections = {
    'repositorio': 'repositório',
    'exercicio': 'exercício',
    'academicos': 'acadêmicos',
    'pos-graduacao': 'pós-graduação',
    'sao': 'são',
    'experimentacao': 'experimentação',
    'nao': 'não',
    'Nao': 'Não',
    'validacao': 'validação',
    'cardiaca': 'cardíaca',
    'referencia': 'referência',
    'servico': 'serviço',
    'ficticia': 'fictícia',
    'informacao': 'informação',
    'clinicos': 'clínicos',
    'medicos': 'médicos',
    'diagnostico': 'diagnóstico',
    'estruturacao': 'estruturação',
    'governanca': 'governança',
    'ingestao': 'ingestão',
    'preprocessamento': 'pré-processamento',
    'ultimo': 'último',
    'conteinerizacao': 'conteinerização',
    'negocio': 'negócio',
    'latencia': 'latência',
    'codigo': 'código',
    'Canonico': 'Canônico',
    'relatorios': 'relatórios',
    'unitarios': 'unitários',
    'integracao': 'integração',
    'Rapido': 'Rápido',
    'Limitacoes': 'Limitações',
    'limitacoes': 'limitações',
    'regiao': 'região',
    'ausencia': 'ausência',
    'avaliacao': 'avaliação',
    'Decisoes': 'Decisões',
    'decisoes': 'decisões',
    'executavel': 'executável',
    'metricas': 'métricas',
    'Metricas': 'Métricas',
    'politica': 'política',
    'Governanca': 'Governança',
    'Historico': 'Histórico',
    'visao': 'visão',
    'Visao': 'Visão',
    'revisao': 'revisão',
    'operacao': 'operação',
    'arquitetural': 'arquitetural',
    'arquiteturais': 'arquiteturais',
    'Minimo': 'Mínimo',
    'consolidacao': 'consolidação',
    'criacao': 'criação',
    'padrao': 'padrão',
    'adocao': 'adoção',
    'funcao': 'função',
    'Restricoes': 'Restrições',
    'restricoes': 'restrições',
    'recomendacao': 'recomendação',
    'evolução': 'evolução',
    'tecnica': 'técnica',
    'configuracao': 'configuração',
    'exportacao': 'exportação',
    'razao': 'razão',
    'abstracao': 'abstração',
    'familia': 'família',
    'producao': 'produção',
    'degradacao': 'degradação',
    'autenticacao': 'autenticação',
    'sera': 'será',
    'esta': 'está',
    'ja': 'já',
    'ate': 'até',
    'tambem': 'também',
    'so': 'só',
    'acoes': 'ações',
    'acao': 'ação',
    'aplicacao': 'aplicação',
    'versao': 'versão',
    'atraves': 'através',
    'apresentacao': 'apresentação',
    'conclusao': 'conclusão',
    'discussao': 'discussão',
    'alem': 'além',
    'atencao': 'atenção',
    'condicoes': 'condições',
    'proxima': 'próxima',
    'proximo': 'próximo',
    'inumeros': 'inúmeros',
    'situacao': 'situação',
    'execucao': 'execução',
    'didaticos': 'didáticos',
    'unica': 'única',
    'unico': 'único',
    'publicos': 'públicos',
    'cenario': 'cenário',
    'basico': 'básico',
    'metodo': 'método',
    'inicio': 'início',
    'dicionario': 'dicionário',
    'modulos': 'módulos',
    'Modulos': 'Módulos',
    'analise': 'análise',
    'Analise': 'Análise',
    'graficos': 'gráficos',
    'tres': 'três',
    'Tres': 'Três',
    'apos': 'após',
    'especifico': 'específico',
    'tecnico': 'técnico',
    'frequencia': 'frequência',
    'consequencia': 'consequência',
    'logistica': 'logística',
    'estatistica': 'estatística',
    'matematica': 'matemática',
    'caracteristicas': 'características',
    'Caracteristicas': 'Características',
    'indice': 'índice',
    'observacao': 'observação',
    'inferencia': 'inferência',
    'lideranca': 'liderança',
    'estrategia': 'estratégia',
    'Estrategia': 'Estratégia',
    'papeis': 'papéis',
    'proprio': 'próprio',
    'propria': 'própria',
    'direcao': 'direção',
    'sessao': 'sessão',
    'sessoes': 'sessões',
    'explicacao': 'explicação',
    'padroes': 'padrões',
    'Inferencia': 'Inferência',
    'Proprio': 'Próprio',
    'Alem': 'Além',
    'Tambem': 'Também',
    'Sera': 'Será',
    'Esta': 'Está',
    'Ate': 'Até',
    'Ja': 'Já',
    'So': 'Só',
    'Unico': 'Único',
    'Unica': 'Única',
    'Publicos': 'Públicos',
    'Clinicos': 'Clínicos',
    'Medicos': 'Médicos',
    'Diagnostico': 'Diagnóstico',
    'Negocio': 'Negócio',
    'Latencia': 'Latência',
    'Codigo': 'Código',
    'Documentacao': 'Documentação',
    'documentacao': 'documentação',
    'diretrize': 'diretriz',
    'diretrizes': 'diretrizes',
    'estrategico': 'estratégico',
    'estrategicos': 'estratégicos',
    'operacionais': 'operacionais',
    'experiencia': 'experiência',
    'Experiencia': 'Experiência',
    'importancia': 'importância',
    'Importancia': 'Importância',
    'relevancia': 'relevância',
    'Relevancia': 'Relevância',
    'referencias': 'referências',
    'Referencias': 'Referências',
    'consequencias': 'consequências',
    'Consequencias': 'Consequências',
    'tendencia': 'tendência',
    'Tendencia': 'Tendência',
    'tendencias': 'tendências',
    'Tendencias': 'Tendências',
    'criterio': 'critério',
    'Criterio': 'Critério',
    'criterios': 'critérios',
    'Criterios': 'Critérios',
    'dominio': 'domínio',
    'Dominio': 'Domínio',
    'historico': 'histórico',
    'necessario': 'necessário',
    'Necessario': 'Necessário',
    'necessarios': 'necessários',
    'Necessarios': 'Necessários',
    'necessaria': 'necessária',
    'Necessaria': 'Necessária',
    'necessarias': 'necessárias',
    'Necessarias': 'Necessárias',
    'primario': 'primário',
    'primarios': 'primários',
    'Primario': 'Primário',
    'secundario': 'secundário',
    'secundarios': 'secundários',
    'diario': 'diário',
    'diarios': 'diários',
    'salario': 'salário',
    'media': 'média',
    'Media': 'Média',
    'medias': 'médias',
    'Medias': 'Médias',
    'presenca': 'presença',
    'Presenca': 'Presença',
    'licenca': 'licença',
    'Licenca': 'Licença',
    'confianca': 'confiança',
    'Confianca': 'Confiança',
    'mudanca': 'mudança',
    'Mudanca': 'Mudança',
    'mudancas': 'mudanças',
    'Mudancas': 'Mudanças',
    'seguranca': 'segurança',
    'Seguranca': 'Segurança',
    'manutencao': 'manutenção',
    'Manutencao': 'Manutenção',
    'prevencao': 'prevenção',
    'Prevencao': 'Prevenção',
    'previsao': 'previsão',
    'Previsao': 'Previsão',
    'previsoes': 'previsões',
    'Previsoes': 'Previsões',
    'precisao': 'precisão',
    'Precisao': 'Precisão',
    'decisao': 'decisão',
    'Decisao': 'Decisão',
    'extensao': 'extensão',
    'Extensao': 'Extensão',
    'compreensao': 'compreensão',
    'Compreensao': 'Compreensão',
    'concessao': 'concessão',
    'Concessao': 'Concessão',
    'implantacao': 'implantação',
    'Implantacao': 'Implantação',
    'saida': 'saída',
    'Saida': 'Saída',
    'saidas': 'saídas',
    'Saidas': 'Saídas',
    'conteudo': 'conteúdo',
    'Conteudo': 'Conteúdo',
    'saude': 'saúde',
    'Saude': 'Saúde',
    'inclusao': 'inclusão',
    'solucao': 'solução',
    'Solucao': 'Solução',
    'solucoes': 'soluções',
    'Solucoes': 'Soluções',
    'construcao': 'construção',
    'construcoes': 'construções',
    'instrucao': 'instrução',
    'instrucoes': 'instruções',
    'geracao': 'geração',
    'operacoes': 'operações',
    'Operacoes': 'Operações',
    'informacoes': 'informações',
    'Informacoes': 'Informações',
    'configuracoes': 'configurações',
    'Configuracoes': 'Configurações',
    'observacoes': 'observações',
    'avaliações': 'avaliações',
    'avaliacoes': 'avaliações',
    'Avaliacoes': 'Avaliações',
    'Atualizacao': 'Atualização',
    'atualizacao': 'atualização',
    'verificacao': 'verificação',
    'Verificacao': 'Verificação',
    'classificacao': 'classificação',
    'Classificacao': 'Classificação',
    'identificacao': 'identificação',
    'Identificacao': 'Identificação',
    'excecao': 'exceção',
    'Excecao': 'Exceção',
    'padronizacao': 'padronização',
    'Padronizacao': 'Padronização',
    'Otimizacao': 'Otimização',
    'otimizacao': 'otimização',
    'maximo': 'máximo',
    'Maximo': 'Máximo',
    'minimo': 'mínimo',
    'arvore': 'árvore',
    'Arvore': 'Árvore',
    'arvores': 'árvores',
    'Arvores': 'Árvores',
    'rapida': 'rápida',
    'rapidas': 'rápidas',
    'rapido': 'rápido',
    'rapidos': 'rápidos',
    'proposito': 'propósito',
    'Proposito': 'Propósito',
    'parametros': 'parâmetros',
    'Parametros': 'Parâmetros',
    'parametro': 'parâmetro',
    'Parametro': 'Parâmetro',
    'numerico': 'numérico',
    'Numerico': 'Numérico',
    'numericos': 'numéricos',
    'Numericos': 'Numéricos',
    'categorico': 'categórico',
    'Categorico': 'Categórico',
    'categoricos': 'categóricos',
    'Categoricos': 'Categóricos',
    'periodo': 'período',
    'Periodo': 'Período',
    'metodos': 'métodos',
    'Metodos': 'Métodos',
    'pratica': 'prática',
    'Pratica': 'Prática',
    'praticas': 'práticas',
    'Praticas': 'Práticas',
    'tecnicas': 'técnicas',
    'Tecnica': 'Técnica',
    'Tecnicas': 'Técnicas',
    'duvida': 'dúvida',
    'Duvida': 'Dúvida',
    'duvidas': 'dúvidas',
    'Duvidas': 'Dúvidas',
    'pagina': 'página',
    'Pagina': 'Página',
    'paginas': 'páginas',
    'Paginas': 'Páginas',
    'maquina': 'máquina',
    'Maquina': 'Máquina',
    'maquinas': 'máquinas',
    'Maquinas': 'Máquinas',
    'concluida': 'concluída',
    'Concluida': 'Concluída',
    'concluido': 'concluído',
    'Concluido': 'Concluído',
    'distribuicao': 'distribuição',
    'Distribuicao': 'Distribuição',
    'Atencao': 'Atenção',
    'Padroes': 'Padrões',
    'atribuicao': 'atribuição',
    'intencao': 'intenção',
    'Intencao': 'Intenção',
    'exibicao': 'exibição',
    'Exibicao': 'Exibição',
    'extracao': 'extração',
    'Extracao': 'Extração',
    'infracao': 'infração',
    'Infracao': 'Infração',
    'projecao': 'projeção',
    'Projecao': 'Projeção',
    'protecao': 'proteção',
    'Protecao': 'Proteção',
    'restricao': 'restrição',
    'Restricao': 'Restrição',
    'transicao': 'transição',
    'Transicao': 'Transição',
    'retencao': 'retenção',
    'Retencao': 'Retenção',
    'variacao': 'variação',
    'Variacao': 'Variação',
    'correcao': 'correção',
    'Correcao': 'Correção',
    'direcoes': 'direções',
    'excecoes': 'exceções',
    'licoes': 'lições',
    'Licoes': 'Lições',
    'opcoes': 'opções',
    'Opcoes': 'Opções',
    'proporcoes': 'proporções',
    'Proporcoes': 'Proporções',
    'reacoes': 'reações',
    'Reacoes': 'Reações',
    'relacoes': 'relações',
    'Relacoes': 'Relações',
    'versoes': 'versões',
    'Versoes': 'Versões',
    'orgaos': 'órgãos',
    'Orgaos': 'Órgãos',
    'orgao': 'órgão',
    'Orgao': 'Órgão',
    'aprovacao': 'aprovação',
    'Aprovacao': 'Aprovação',
    'bloqueatoria': 'bloqueatória',
}

def process_file(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    blocks = re.split(r'(```.*?```)', content, flags=re.DOTALL)
    
    for i in range(len(blocks)):
        if not blocks[i].startswith('```'):
            text = blocks[i]
            
            # Phrase logic
            text = re.sub(r'\ba empresa\b', 'à empresa', text)
            text = re.sub(r'\be um\b', 'é um', text)
            text = re.sub(r'\be uma\b', 'é uma', text)
            text = re.sub(r'\be de\b', 'é de', text)
            text = re.sub(r'\bque e\b', 'que é', text)
            text = re.sub(r'\bnao e\b', 'não é', text)
            text = re.sub(r'\bcomo e\b', 'como é', text)
            text = re.sub(r'\bou e\b', 'ou é', text)
            text = re.sub(r'\be o\b', 'é o', text)
            text = re.sub(r'\be a\b', 'é a', text)
            text = re.sub(r'\be os\b', 'é os', text)
            text = re.sub(r'\be as\b', 'é as', text)
            text = re.sub(r'\bisto e\b', 'isto é', text)
            text = re.sub(r'\bisso e\b', 'isso é', text)
            text = re.sub(r'\baquisicao\b', 'aquisição', text)
            
            # Additional corrections not strictly dict
            text = re.sub(r'\bnao\b', 'não', text) # just in case
            
            # Word iterations
            for bad, good in corrections.items():
                if bad == 'e': continue
                text = re.sub(r'\b' + bad + r'\b', good, text)
            
            blocks[i] = text

    new_content = ''.join(blocks)
    if new_content != content:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(new_content)
        print(f"Fixed {filepath}")

for root, dirs, files in os.walk('.'):
    if '.venv' in root or '.pytest_cache' in root:
        continue
    for file in files:
        if file.endswith('.md'):
            process_file(os.path.join(root, file))
